import type { Item } from '../types';

export const mockItems: Item[] = [
  {
    id: "1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: "003",
    specNumber: "BD-200",
    itemName: "Drapery",
    vendor: "ABC Drapery",
    shipTo: "Sunrise Inn",
    qty: 2,
    phase: "01",
    price: 4800.00,
    shipNotes: "Delicate prod...",
  },
  {
    id: "2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: "003",
    specNumber: "BD-200",
    itemName: "Drapery",
    vendor: "ABC Drapery",
    shipTo: "Sunrise Inn",
    qty: 2,
    phase: "01",
    price: 4800.00,
    shipNotes: "Delicate prod...",
  },
  {
    id: "3",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: "003",
    specNumber: "BD-200",
    itemName: "Drapery",
    vendor: "ABC Drapery",
    shipTo: "Sunrise Inn",
    qty: 2,
    phase: "01",
    price: 4800.00,
    shipNotes: "Delicate prod...",
  },
  {
    id: "4",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: "003",
    specNumber: "BD-200",
    itemName: "Drapery",
    vendor: "ABC Drapery",
    shipTo: "Sunrise Inn",
    qty: 2,
    phase: "01",
    price: 4800.00,
    shipNotes: "Delicate prod...",
  },
  {
    id: "5",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: "003",
    specNumber: "BD-200",
    itemName: "Drapery",
    vendor: "ABC Drapery",
    shipTo: "Sunrise Inn",
    qty: 2,
    phase: "01",
    price: 4800.00,
    shipNotes: "Delicate prod...",
  },
  {
    id: "6",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: "004",
    specNumber: "BD-201",
    itemName: "Curtains",
    vendor: "XYZ Fabrics",
    shipTo: "Ocean View",
    qty: 4,
    phase: "02",
    price: 3200.00,
    shipNotes: "Handle with care",
  },
  {
    id: "7",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: "005",
    specNumber: "BD-202",
    itemName: "Blinds",
    vendor: "Shade Masters",
    shipTo: "Mountain Lodge",
    qty: 6,
    phase: "01",
    price: 1800.00,
    shipNotes: "Fragile items",
  },
  {
    id: "8",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: "006",
    specNumber: "BD-203",
    itemName: "Valance",
    vendor: "ABC Drapery",
    shipTo: "Sunrise Inn",
    qty: 3,
    phase: "03",
    price: 950.00,
    shipNotes: "Rush order",
  },
  // Generate more items for pagination demo
  ...Array.from({ length: 22 }, (_, i) => ({
    id: `${9 + i}`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    itemNumber: `00${7 + i}`,
    specNumber: `BD-${204 + i}`,
    itemName: ["Drapery", "Curtains", "Blinds", "Valance", "Shades"][i % 5],
    vendor: ["ABC Drapery", "XYZ Fabrics", "Shade Masters", "Home Decor Co"][i % 4],
    shipTo: ["Sunrise Inn", "Ocean View", "Mountain Lodge", "City Hotel"][i % 4],
    qty: Math.floor(Math.random() * 10) + 1,
    phase: `0${(i % 3) + 1}`,
    price: Math.floor(Math.random() * 5000) + 500,
    shipNotes: ["Delicate prod...", "Handle with care", "Fragile items", "Rush order"][i % 4],
  })),
];

